### PR TITLE
Update black

### PR DESCRIPTION
**Pull request by dchung0741**
All the poetry.lock files in the packages and the root have been updated to version 23.1.0

### CODE REVIEW

**Comment by dchung0741** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dchung0741** [comment]
I have migrated the PR for updating the all the `black` version to 23.1.0 to the public repository

**Comment by kwkbtr** [comment]
Jupyter Notebook files haven't been subject to formatting by `black` and I don't see strong needs to do that.
Could you restore those files?

**Comment by dchung0741** [comment]
> Jupyter Notebook files haven't been subject to formatting by `black` and I don't see strong needs to do that. Could you restore those files?

Just to make sure. 
As it is migrated to the public repo PR, I should clone the public repo and reset all the jupyter notebooks there?

**Comment by kwkbtr** [comment]
I guess you can do the restore on the private one and push to the public repo again.

**Comment by dchung0741** [comment]
> I guess you can do the restore on the private one and push to the public repo again.

I see. I just restored all the jupyter notebook files to the their original formats before reformatted by black.

**Review by kwkbtr — APPROVED** [review]
👍

**Pull request merged**
