### PR TITLE
Update qulacs version to 0.5.6

### PR DESCRIPTION
**Pull request by dchung0741**
Update `qulacs` to version 0.5.6, and fix `mypy` errors in `quri_parts.qulacs`

### CODE REVIEW

**Comment by dchung0741** [comment]
Errors related to DensityMatrix cannot be "casted away".
image
Cannot figure out how to cast something to `ndarray[complexfloating[_64Bit, _64Bit], Tuple[int, ...]]`

**Comment by kwkbtr** [comment]
It seems that the annotation in Qulacs is incorrect in this case too...
https://github.com/qulacs/qulacs/blob/5c654d21037e8ce82db0a69a398d486044a4fcbc/pysrc/qulacs/__init__.pyi#L999
The first type variable should be `_ShapeType`
https://github.com/numpy/numpy/blob/8cec82012694571156e8d7696307c848a7603b4e/numpy/__init__.pyi#L1482

**Comment by kwkbtr** [comment]
I posted an issue to Qulacs repo: https://github.com/qulacs/qulacs/issues/537
At the moment we may need to exclude the affected lines from type checking.

**Comment by dchung0741** [comment]
Thanks for raising such issue to qulacs!

I tried to add `#type: ignore` after the lines that imports `qulacs`, but `mypy` complains that `Unused "type: ignore" comment`. Could it be that I have completely misunderstood the usage of `#type: ignore`? Or is there a better way to ignore it?

**Comment by kwkbtr** [comment]
Please check mypy reference.

**Comment by dchung0741** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dchung0741** [comment]
1. Fixed `mypy` issue with `# type: ignore` comments
2. Fixed author email issue

**Comment by kwkbtr** [comment]
Addressed in #60

**Pull request closed without merging**
