### PR TITLE
Overlap estimator

### PR DESCRIPTION
**Pull request by ThomasenQunasys**
### changes:
- Added an overlap estimator for both state-vector (qulacs) and sampling simulator
- Added a weighted overlap estimator (useful for VQD) for both state-vector (qulacs) and sampling simulator
- Added a function to get inverse circuits

### comments:
This allows the user to obtain estimates of wave-function overlaps as an example
```
from quri_parts.core.estimator.sampling import create_sampling_overlap_estimator
from quri_parts.core.sampling import create_concurrent_sampler_from_sampling_backend
n_shots = 10000
sampler = create_concurrent_sampler_from_sampling_backend(backend)
estimator = create_sampling_overlap_estimator(n_shots, sampler)
estimate = estimator(ket, bra)
print(estimate.value)
print(estimate.error)
```

### CODE REVIEW

**Comment by ThomasenQunasys** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ThomasenQunasys** [comment]
recheck

**Comment by kwkbtr** [comment]
I guess the least time-consuming way may be to squash all the commits into one commit which is commited by @ThomasenQunasys (not the other one).

**Comment by ThomasenQunasys** [comment]
recheck

**Comment by ThomasenQunasys** [comment]
Ok to merge?

**Comment by kwkbtr** [comment]
- Removal of `test_inverse_gate.py` seems to have gone. From the diff statistics, I guess it is the only missing change.
- Please edit the pull request comment so that anyone can know what this PR is for.

**Comment by kwkbtr** [comment]
Let's not mention an issue in a private repository.

**Review by kwkbtr — APPROVED** [review]
👍

**Pull request merged**
